---

dist: bionic

language: python
python:
  - 3.6
services: docker

env:
  global:
    - ROLE_NAME: latex
  matrix:
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

install:
  - pip install molecule ansible-lint flake8 docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
