---

- name: establish texlive repo
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version < '16.10'
  apt_repository:
    repo: "ppa:jonathonf/texlive"
    state: present
    filename: texlive
  tags: install

- name: establish package
  become: true
  package:
    name: "{{ package_map[latex_package] }}"
    state: present
  tags: install

- name: establish latex_extensions
  become: true
  package:
    name: "{{ latex_extensions }}"
    state: present
  tags: install

- name: establish latex_editors
  become: true
  package:
    name: "{{ latex_editors }}"
    state: present
  tags: install
