---

- name: establish package
  become: yes
  package:
    name: "{{ package_map[package] }}"
    state: present
  tags: install

- name: establish extensions
  become: yes
  package:
    name: "{{ extensions | map('regex_replace', '(.*)', 'texlive-\\1') | list }}"
    state: present
  tags: install

- name: establish editors
  become: yes
  package:
    name: "{{ editors }}"
    state: present
  tags: install

