---

- name: establish package
  become: yes
  package:
    name: "{{ package_map[package] }}"
    state: present

- name: establish extensions
  become: yes
  package:
    name: "texlive-{{ item }}"
    state: present
  loop: "{{ extensions }}"

- name: establish editors
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ editors }}"

