---

- name: add texlive repo
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version < '16.10'
  apt_repository:
    repo: "ppa:jonathonf/texlive"
    state: present
    filename: texlive
  tags: install

- name: establish package
  become: true
  package:
    name: "{{ package_map[package] }}"
    state: present
  tags: install

- name: establish extensions
  become: true
  package:
    name: "{{ extensions }}"
    state: present
  tags: install

- name: establish editors
  become: true
  package:
    name: "{{ editors }}"
    state: present
  tags: install
