---

- name: Converge
  hosts: all
  roles:
    - role: latex
      vars:
        latex_package: 'base'
        latex_extensions:
          - texlive-extra-utils
        latex_editors:
          - texstudio
